# Basic Site Settings
title: "Agovia Edusphere Ventures"
description: "We connect people to cars, countries, and knowledge."
url: "https://agoviaedusphere.github.io"
baseurl: ""  # No subdirectory

# Author/Business Info
author:
  name: "Agovia Edusphere Ventures"
  bio: "Global access to cars, travel, and learning."
  email: "agyeahmotors@gmail.com"
  location: "Ghana"
  # linkedin: "company/agovia-edusphere-ventures"
  linkedin: https://www.linkedin.com/company/agovia-edusphere-ventures/
  # linkedin:"https://www.linkedin.com/company/agovia-edusphere-ventures/?viewAsMember=true"
  instagram: ""
  facebook: ""
  # github: "agoviaedusphere"

# Pages to Include
include:
  - _pages
  - files

# Collections (None needed unless you later want blog or product listings)
collections: {}

# Defaults for all pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Navigation (define in _data/navigation.yml if needed)
# You can also just hard-code links on the homepage or header if preferred

# Plugins and Features
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap

whitelist:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:title/
timezone: Etc/UTC

# Social Sharing (optional)
og_image:  # default image
og_description: "Car importation, education consulting, and travel solutions from Ghana to the world."

# Compression
compress_html:
  clippings: all
  ignore:
    envs: development
